Authentication and Authorization chapter
w3c/automotive pull request #314
Opened 2019-11-06 13:47 UTC by danielwilms

**CORE**: created with input from VIWI. 
**TRANSPORT**: updated to match current VSS modelling.

Fixes #308

2019-11-07 09:12 UTC, UlfBj approved these changes
+1

2019-11-07 10:25 UTC, PatrickCQ commented
Usage of Transport Document unclear to me.
See issue https://github.com/w3c/automotive/issues/313

2019-11-07 10:46 UTC, UlfBj commented
>> Usage of Transport Document unclear to me.

In #313 I think you clarify the Transport document usage correctly yourself, so what is unclear?
Gen2 specifies two transport protocols, HTTP and WebSocket, and the specifics of applying the Gen2 messaging to each of these protocols needs to be described somewhere. @PatrickCQ Would you rather see it all in one document?

2019-11-07 11:33 UTC, PatrickCQ commented
> In #313 I think you clarify the Transport document usage correctly yourself, so what is unclear?
> Gen2 specifies two transport protocols, HTTP and WebSocket, and the specifics of applying the Gen2 messaging to each of these protocols needs to be described somewhere. @PatrickCQ Would you rather see it all in one document?

I would like to see it in 3 separate documents as summarized in https://github.com/w3c/automotive/issues/313.

2019-11-07 11:57 UTC, UlfBj commented
>> I would like to see it in 3 separate documents as summarized in #313.

That is an opinion that is suitable for discussion in the WG, it has not much to do with this PR.

2019-11-07 12:06 UTC, PatrickCQ requested changes
Please add changes to the corresponding documents as discussed https://lists.w3.org/Archives/Member/member-automotive/2018Nov/0006.html

2019-11-07 12:17 UTC, UlfBj commented
>> Please add changes to the corresponding documents as discussed https://lists.w3.org/Archives/Member/member-automotive/2018Nov/0006.html

That is a long mail thread, I think you need to be more specific about what changes mentioned there you think should be added.

2019-11-07 12:22 UTC, PatrickCQ commented
> > > Please add changes to the corresponding documents as discussed https://lists.w3.org/Archives/Member/member-automotive/2018Nov/0006.html
> 
> That is a long mail thread, I think you need to be more specific about what changes mentioned there you think should be added.

Please use three documents:
- Core: as is
- Transport: with general requirements to a transport protocol
- Transport_HTTPS.WS (new): to describe the specific handling of the requirements from Transport for the HTTP and WS combination

2019-11-07 13:17 UTC, danielwilms commented
Hi guys,

I try to jump in as moderator, if you allow :) @PatrickCQ, please mark in the document, which part you want to see in which document. If it's clear to you then please add something like 
```
start <document where it should go to>
...
end  <document where it should go to>
``` 
Then it's much more efficient to discuss it. If @UlfBj agrees, he can move it. If not we bring it up in the call. We have to remember, that the others agreed already to the change, with the issues, we raised in the #309.

2019-11-07 13:18 UTC, UlfBj commented
>> Please use three documents:
Core: as is
Transport: with general requirements to a transport protocol
Transport_HTTPS.WS (new): to describe the specific handling of the requirements from Transport for the HTTP and WS combination

I think this should be discussed in the WG first. If I am not mistaken the WG recently decided to go with the existing Gen2 documents, so if that decision should be changed it needs to be discussed by the WG first. 
I think you are bringing this up in the wrong context, it is a WG issue and is not related to this PR.

2019-11-07 13:22 UTC, PatrickCQ commented
> I think you are bringing this up in the wrong context, it is a WG issue and is not related to this PR.

I agree. https://github.com/w3c/automotive/issues/313 can be closed with the conclusion from the the discussion in the working group.

2019-11-07 13:34 UTC, UlfBj commented
>> I think you are bringing this up in the wrong context, it is a WG issue and is not related to this PR.
I agree.

With that statement I assume you will remove your change request and approve this PR.

2019-11-07 19:39 UTC, MagnusGun commented
@PatrickCQ, I don't understand the logic of separating the spec into multiple documents can you please elaborate

2019-11-08 12:31 UTC, PatrickCQ commented
> @PatrickCQ, I don't understand the logic of separating the spec into multiple documents can you please elaborate

please see https://github.com/w3c/automotive/issues/313

2019-11-08 13:08 UTC, MagnusGun commented
> > @PatrickCQ, I don't understand the logic of separating the spec into multiple documents can you please elaborate
> 
> please see #313

I have read #313 and I don't have any problems with the separation of topics but I dont get why we need to have them as separate documents instead of chapters in the same document...

2019-11-12 15:29 UTC, tguild commented
@MagnusGun @PatrickCQ whether to split out into transport protocol specific documents should depend on how much clarification is needed for each. I would mildly prefer moderate sized chapters to additional documents. Large chapters can indeed become unwieldy and warrant spinning off separate documents. It is possible to defer and separate later unless we have an early indication the HTTP/WS specific aspects will be sizable

2019-11-19 20:22 UTC, merged

2019-11-19 20:23 UTC, tguild commented
https://www.w3.org/2019/11/19-auto-minutes

issue whether to have chapter or separate protocol documents in issue 313